liip_imagine:

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../private"

    # define your filter sets under this option
    filter_sets:

        home_slider:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                grayscale: ~
                thumbnail:
                    size:          [800, 800]
                    mode:          outbound
                    allow_upscale: true

        group_presentation_main:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [800, 1200]
                    mode:          outbound
                    allow_upscale: true

        group_presentation_slider:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [600, 380]
                    mode:          outbound
                    allow_upscale: true

        group_history:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [700, 650]
                    mode:          outbound
                    allow_upscale: true

        group_history_2:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [580, 500]
                    mode:          outbound
                    allow_upscale: true

        group_value_image:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [910, 610]
                    mode:          outbound
                    allow_upscale: true

        group_value_picto:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [470, 470]
                    mode:          outbound
                    allow_upscale: true

        expertise_wine:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [1800, 700]
                    mode:          outbound
                    allow_upscale: true

        expertise_wine_article:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [700, 1000]
                    mode:          outbound
                    allow_upscale: true

        expertise_thumbnail:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [520, 520]
                    mode:          outbound
                    allow_upscale: true

        expertise_subsidiary_logo:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [450, 110]
                    mode:          outbound
                    allow_upscale: true

        post_thumbnail:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [570, 570]
                    mode:          outbound
                    allow_upscale: true

        single_post:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [1550, 750]
                    mode:          outbound
                    allow_upscale: true

        contact_logo:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                strip: ~
                thumbnail:
                    size:          [400, 200]
                    mode:          outbound
                    allow_upscale: false
